# zshrc - for interactive shells

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load in ~/.oh-my-zsh/themes/
# https://github.com/sindresorhus/pure
ZSH_THEME="refined"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(brew colored-man-pages)

alias zigdev="/Users/nathany/Development/zig/zig/build/stage3/bin/zig"
# alias gotip="/Users/nathany/src/go.googlesource.com/gotip/bin/go"

source $ZSH/oh-my-zsh.sh
unsetopt correct_all

# RCM
export DOTFILES_DIRS=$HOME/src/github.com/nathany/setup/dotfiles

# export EDITOR="subl -w"
# export EDITOR="code --wait"
export EDITOR="zed --wait"

# cd..
export CDPATH=.:$HOME/src/github.com:$HOME/src/github.com/nathany

# eval "$(gh alias -s)"

# Use Ruby from Homebrew
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"

# LLVM
# export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
