# zshrc - for interactive shells

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load in ~/.oh-my-zsh/themes/
# https://github.com/sindresorhus/pure
ZSH_THEME="refined"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(brew colored-man-pages)

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
# alias pmp="osascript ~/Development/styleterm.scpt 'Red Sands'; ssh deploy@primus_production; osascript ~/Development/styleterm.scpt 'Pro'"

# alias go4="/Users/nathany/src/go.googlesource.com/go1.4/bin/go"
# alias go9="/Users/nathany/src/go.googlesource.com/go1.9/bin/go"
# alias go10="/Users/nathany/src/go.googlesource.com/go1.10/bin/go"
# alias go11="/Users/nathany/src/go.googlesource.com/go1.11/bin/go"
# alias go12="/Users/nathany/src/go.googlesource.com/go1.12/bin/go"
# alias go13="/Users/nathany/src/go.googlesource.com/go1.13/bin/go"
# alias go14="/Users/nathany/src/go.googlesource.com/go1.14/bin/go"
# alias go15="/Users/nathany/src/go.googlesource.com/go1.15/bin/go"
# alias go16="/Users/nathany/src/go.googlesource.com/go1.16/bin/go"
# alias gotip="/Users/nathany/src/go.googlesource.com/gotip/bin/go"

source $ZSH/oh-my-zsh.sh
unsetopt correct_all

# RCM
export DOTFILES_DIRS=$HOME/src/github.com/nathany/setup/dotfiles

export EDITOR="subl -w"

# cd..
export CDPATH=.:$HOME/src/github.com:$HOME/src/github.com/nathany

# eval "$(gh alias -s)"
